# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-18 00:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mlearn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlearn',
            name='image',
            field=models.ImageField(default=datetime.datetime(2016, 6, 18, 0, 26, 19, 660176, tzinfo=utc), upload_to='photos'),
            preserve_default=False,
        ),
    ]
